CREATE TABLE IF NOT EXISTS scheduled_tasks_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name TEXT NOT NULL,
  run_window TEXT NOT NULL,
  status TEXT NOT NULL,
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  error_message TEXT,
  details JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (job_name, run_window)
);

CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_log_job_window
  ON scheduled_tasks_log (job_name, run_window DESC);

CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_log_status
  ON scheduled_tasks_log (status);
